services:
  todo-printer:
    build: .
    environment:
      - DISCORD_API_TOKEN=${DISCORD_API_TOKEN}
      - GITHUB_PAT=${GITHUB_PAT}
      - GEMINI_KEY=${GEMINI_KEY}
    restart: unless-stopped
    ports:
      - 8333:8333
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    privileged: true
